services:
  neo4j:
    container_name: mshack-organigram-neo4j
    image: docker.io/neo4j:5
    ports:
      - "7474:7474"
      - "7687:7687"
    environment:
      - "NEO4J_AUTH=none"
    volumes:
      - "./docker_volumes/neo4j:/data"
  web:
    container_name: mshack-organigram-web
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "${PORT-3000}:3000"
    volumes:
      - ./node_modules:/app/node_modules
